objects/Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Last_Attempt_Time__c</fullName>
        <label>Last_Attempt_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Next_Run_Time__c</fullName>
        <label>Next_Run_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Ids__c</fullName>
        <description>Opportunity/Order Id</description>
        <label>Record_Ids</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <label>Retry_Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Integration_Log</label>
    <nameField>
        <label>Integration_Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RetryIntegrationBatch.cls
public with sharing class RetryIntegrationBatch implements Database.Batchable<SObject>, Database.Stateful{
    
    public Database.QueryLocator start(Database.BatchableContext bc){

        return Database.getQueryLocator(
            [
                SELECT Id,                   
                   Record_Ids__c,
                   Retry_Count__c,
                   Status__c,
                   Next_Run_Time__c,
                   Last_Attempt_Time__c
            FROM Integration_Log__c
            WHERE Status__c = 'Failed'
            AND Retry_Count__c < 3
            AND Next_Run_Time__c <= :System.now()
            ]
        );

    }

    public void execute(Database.BatchableContext bc, List<SObject> scope){
        Set<Id> orderIds = new Set<Id>();
        List<Integration_Log__c> logs = (List<Integration_Log__c>) scope;

        for(Integration_Log__c log : logs){

            log.Status__c = 'In Progress';           
            log.Last_Attempt_Time__c = System.now();
            // log.Next_Run_Time__c = getNextRunTime(log.Retry_Count__c);
            // log.Retry_Count__c += 1;
            
            if(String.isNotBlank(log.Record_Ids__c)){
            orderIds.addAll((Set<Id>)JSON.deserialize(log.Record_Ids__c, Set<Id>.class));
            }
        }
        update logs;
        if(!orderIds.isEmpty()){
            
            System.enqueueJob(new OrderIntegrationQueueable(orderIds));
        }

    }


    public void finish(Database.BatchableContext bc){

    }


}